name: oasis
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - requests

  # Semantic Web / Ontology
  - rdflib
  - sparqlwrapper

  # Pip-only packages (not on conda)
  - pip:
    - owlready2
    - web3
