name: Dependency Snapshot

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Component detection
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.1
